function k(a){this.input=a.input;this.a=a.b.a;this.b=a.b;this.speed=3;this.e=[0,0,120];this.o=[0,0,0];this.ea=[0,1,0];this.d=quat.create()};function l(a){this.g=this.H();this.input=new m;this.input.f("forward","W");this.input.f("backward","S");this.input.f("left","A");this.input.f("right","D");this.input.f("up","R");this.input.f("down","F");this.b=new n(a,this.g,this);this.j=this.b.j;this.r=this.r.bind(this);console.dir(this)}goog.ma("Engine",l);l.prototype.H=function(){var a=new Stats;a.ta(1);document.body.appendChild(a.ka);return a};goog.C(l.prototype,"initStats",l.prototype.H);
l.prototype.X=function(a,b){p(this.j,a,function(){var a=this.j.q("manifest.json");this.K(a.oa);"function"==typeof b&&b()}.bind(this))};goog.C(l.prototype,"loadGameData",l.prototype.X);l.prototype.K=function(a){a=this.b.j.q(a);this.b.w=new q(a,this.b.a);console.log(a)};goog.C(l.prototype,"loadScene",l.prototype.K);
l.prototype.r=function(){this.g&&this.g.ia();var a=this.b,b=a.a;if(a.w){b.enable(b.DEPTH_TEST);a.c=a.Q[0];b.useProgram(a.c);b.bindFramebuffer(b.FRAMEBUFFER,a.W);a.D.la(a.h);b.framebufferTexture2D(b.FRAMEBUFFER,a.h[0],b.TEXTURE_2D,a.I,0);b.framebufferTexture2D(b.FRAMEBUFFER,a.h[1],b.TEXTURE_2D,a.A,0);b.framebufferTexture2D(b.FRAMEBUFFER,a.h[2],b.TEXTURE_2D,a.M,0);b.framebufferTexture2D(b.FRAMEBUFFER,b.DEPTH_STENCIL_ATTACHMENT,b.TEXTURE_2D,a.B,0);b.viewport(0,0,b.canvas.width,b.canvas.height);b.clear(a.a.COLOR_BUFFER_BIT|
a.a.DEPTH_BUFFER_BIT);var c=a.T,d;c.input.action("forward")&&(d=vec3.create(),vec3.R(d,c.e,c.o),10<vec3.ua(d)&&(vec3.normalize(d,d),vec3.scale(d,d,7),vec3.R(c.e,c.e,d)));c.input.action("backward")&&(d=vec3.create(),vec3.R(d,c.e,c.o),vec3.normalize(d,d),vec3.scale(d,d,7),vec3.add(c.e,c.e,d));c.input.action("left")&&quat.ca(c.d,c.d,.03);c.input.action("right")&&quat.ca(c.d,c.d,-.03);c.input.action("up")&&quat.ba(c.d,c.d,.03);c.input.action("down")&&quat.ba(c.d,c.d,-.03);d=vec3.create();var h=vec3.create();
vec3.da(d,c.e,c.d);vec3.da(h,c.ea,c.d);mat4.Y(c.b.l,d,c.o,h);r(a);s(a.w,a.c,mat4.clone(a.s));a.c=a.Q[1];b.bindFramebuffer(b.FRAMEBUFFER,null);b.disable(b.DEPTH_TEST);b.clear(a.a.COLOR_BUFFER_BIT|a.a.DEPTH_BUFFER_BIT);b.useProgram(a.c);b.activeTexture(b.TEXTURE0);b.bindTexture(b.TEXTURE_2D,a.I);b.activeTexture(b.TEXTURE1);b.bindTexture(b.TEXTURE_2D,a.B);b.activeTexture(b.TEXTURE2);b.bindTexture(b.TEXTURE_2D,a.A);b.activeTexture(b.TEXTURE3);b.bindTexture(b.TEXTURE_2D,a.M);for(c=0;4>c;++c)b.uniform1i(b.getUniformLocation(a.c,
"uSampler"+c),c);r(a);b=a.a;a.v||(a.v=b.createBuffer(),c=new Float32Array([-1,-1,0,1,-1,0,-1,1,0,-1,1,0,1,-1,0,1,1,0]),b.bindBuffer(b.ARRAY_BUFFER,a.v),b.bufferData(b.ARRAY_BUFFER,c,b.STATIC_DRAW));b.bindBuffer(b.ARRAY_BUFFER,a.v);b.vertexAttribPointer(a.c.m,3,b.FLOAT,!1,0,0);b.drawArrays(b.TRIANGLES,0,6)}this.g&&this.g.end();window.requestAnimationFrame(this.r,this.b.canvas)};function m(){this.p=new Uint8Array(256);document.addEventListener("keydown",this.J.bind(this));document.addEventListener("keyup",this.J.bind(this));this.debug=!0;this.n={}}m.prototype.f=function(a){if(!(2>arguments.length)){var b=Array.prototype.slice.call(arguments,1),c;c=[];var d;for(d=0;d<b.length;++d)"string"===typeof b[d]&&1===b[d].length&&(b[d]=b[d].charCodeAt(0)),"number"===typeof b[d]&&c.push(b[d]);this.n[a]=c}};
m.prototype.action=function(a){var b=!1,c=this.n[a];for(a=0;a<c.length;++a)b=b||this.p[c[a]];return b};m.prototype.J=function(a){this.debug&&console.log(a.type,a.keyCode);switch(a.type){case "keyup":this.p[a.keyCode]=0;break;case "keydown":this.p[a.keyCode]=1}console.log(JSON.stringify(this.n))};function q(a,b){this.data=a;var c=this.a=b,d,h,e;for(d in this.data.k)e=this.data.k[d],e.S=c.createBuffer(),c.bindBuffer(c.ARRAY_BUFFER,e.S),c.bufferData(c.ARRAY_BUFFER,new Float32Array(e.ya),c.STATIC_DRAW),e.i=[],e.i=e.i.concat.apply(e.i,e.na),e.G=c.createBuffer(),c.bindBuffer(c.ELEMENT_ARRAY_BUFFER,e.G),c.bufferData(c.ELEMENT_ARRAY_BUFFER,new Uint16Array(e.i),c.STATIC_DRAW),e.N=c.createBuffer(),c.bindBuffer(c.ARRAY_BUFFER,e.N),c.bufferData(c.ARRAY_BUFFER,new Float32Array(e.ra),c.STATIC_DRAW);for(d in this.data.$){c=
this.data.$[d];c.pa={};c.va={};c.ja={};for(h in c.u)e=c.u[h].key.slice(1).split("."),c[e[0]][e[1]]=c.u[h].value;delete c.u}console.dir(this)}
function s(a,b,c,d){var h,e=mat4.create();c||(c=mat4.create(),mat4.F(c));d?(mat4.xa(e,d.wa),mat4.qa(c,c,e)):d=a.data.sa;if(d.k)for(h in a.a.uniformMatrix4fv(b.L,!1,c),d.k){var e=b,g=a.a,f=a.data.k[d.k[h]];g.bindBuffer(g.ARRAY_BUFFER,f.S);g.vertexAttribPointer(e.m,3,g.FLOAT,!1,0,0);g.bindBuffer(g.ARRAY_BUFFER,f.N);g.vertexAttribPointer(e.t,3,g.FLOAT,!1,0,0);g.bindBuffer(g.ELEMENT_ARRAY_BUFFER,f.G);g.drawElements(g.TRIANGLES,f.i.length,g.UNSIGNED_SHORT,0)}if(d.children)for(h in d.children)s(a,b,mat4.clone(c),
d.children[h])}
function n(a,b,c){window.requestAnimationFrame=window.requestAnimationFrame||window.mozRequestAnimationFrame||window.webkitRequestAnimationFrame||window.msRequestAnimationFrame;a=document.getElementById(a);b&&(this.g=b);this.j=new t;c.b=this;this.a=void 0;this.O=mat4.create();this.s=mat4.create();this.l=mat4.create();mat4.F(this.l);try{this.P=a.getContext("experimental-webgl")||a.getContext("webgl")}catch(d){}this.P?(this.a=this.P,this.V=this.a.getExtension("WEBGL_depth_texture"),this.D=this.a.getExtension("WEBGL_draw_buffers"),
this.a.getExtension("OES_texture_float")):console.error("Unable to load webgl");if(this.a){u(this);this.a.clearColor(0,0,0,1);b=this.a;this.W=b.createFramebuffer();this.I=v(this,b.RGBA,b.UNSIGNED_BYTE);this.B=v(this,b.DEPTH_STENCIL,this.V.ga);this.A=v(this,b.RGBA,b.FLOAT);this.M=v(this,b.RGBA,b.FLOAT);this.h=[];for(b=0;4>b;++b)this.h[b]=this.D.fa+b;mat4.perspective(this.O,45,this.a.canvas.width/this.a.canvas.height,.1,1E4);mat4.F(this.s);mat4.Y(this.l,[0,0,120],[0,0,0],[0,1,0]);this.a.enable(this.a.DEPTH_TEST);
this.T=new k(c);console.dir(this.a.getSupportedExtensions())}}
function u(a){function b(a){var b,c;b=document.getElementById(a);if(!b)return null;a="";for(c=b.firstChild;c;)c.nodeType===c.TEXT_NODE&&(a+=c.textContent),c=c.nextSibling;if("x-shader/x-fragment"===b.type)b=d.createShader(d.FRAGMENT_SHADER);else if("x-shader/x-vertex"===b.type)b=d.createShader(d.VERTEX_SHADER);else return null;d.shaderSource(b,a);d.compileShader(b);if(!d.getShaderParameter(b,d.COMPILE_STATUS)){a=a.split("\n");for(c=0;c<a.length;++c)a[c]=c+1+": "+a[c];console.log(a.join("\n"));alert("An error occurred compiling the shaders: "+
d.getShaderInfoLog(b));return null}return b}function c(a,c){var e=d.createProgram(),f=b(c),g=b(a);d.attachShader(e,g);d.attachShader(e,f);d.linkProgram(e);d.getProgramParameter(e,d.LINK_STATUS)||console.error("Unable to initialize the shader program.");return e}var d=a.a,h=c("shader-vs","shader-fs"),e=c("last-vs","last-fs");a.a.useProgram(h);var e=[h,e],g,f;for(g=0;g<e.length;++g)f=e[g],a.a.useProgram(f),f.m=a.a.getAttribLocation(f,"aVertexPosition"),f.t=a.a.getAttribLocation(f,"aNormal"),a.a.enableVertexAttribArray(f.m),
a.a.enableVertexAttribArray(f.t),-1!==f.m&&-1!==f.t||console.log("Problem in shader:"+g),f.aa=a.a.getUniformLocation(f,"uPMatrix"),f.L=a.a.getUniformLocation(f,"uMVMatrix"),f.Z=a.a.getUniformLocation(f,"uLookAt");a.Q=e;a.c=h}function r(a){var b=a.a;b.uniformMatrix4fv(a.c.aa,!1,a.O);b.uniformMatrix4fv(a.c.L,!1,a.s);b.uniformMatrix4fv(a.c.Z,!1,a.l);b.uniform2fv(b.getUniformLocation(a.c,"resolution"),[b.canvas.width,b.canvas.height])}
function v(a,b,c){var d;a=a.a;var h=a.createTexture();d||(d=b);a.bindTexture(a.TEXTURE_2D,h);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_S,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_WRAP_T,a.CLAMP_TO_EDGE);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MIN_FILTER,a.NEAREST);a.texParameteri(a.TEXTURE_2D,a.TEXTURE_MAG_FILTER,a.NEAREST);a.texImage2D(a.TEXTURE_2D,0,b,a.canvas.width,a.canvas.height,0,d,c,null);return h};function t(){}function w(a,b){var c=new XMLHttpRequest;c.open("GET",a,!0);c.responseType="arraybuffer";c.onload=function(){b(c.response,c.responseType)};c.send()}t.prototype.load=function(a){return this.U.file(a).ha()};function p(a,b,c){w(b,function(a){this.U=new JSZip(a);c()}.bind(a))}t.prototype.q=function(a){a=JSON.parse(this.load(a));console.log(a);return a};function t(){}t.prototype.load=function(a,b){var c=new XMLHttpRequest;c.open("GET",a,!1);c.onload=function(){b(c.response,c.responseType)}};t.prototype.q=function(a,b){this.load(a,function(a,d){a=JSON.parse(a);b(a,d)},"JSON")};
